### GET /

GET http://localhost:5000

### Register a user POST /auth/register
POST http://localhost:5000/auth/register
Content-Type: application/json


{

    "username":"testuser1@gmail.com",
    "password": "12345678"

}

### Login a user post /auth/login
POST http://localhost:5000/auth/login
Content-Type: application/json


{

    "username":"testuser1@gmail.com",
    "password": "12345678"

}

### Get all todos GET /todos
GET http://localhost:5000/todos
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzQzOTY1ODg4LCJleHAiOjE3NDQwNTIyODh9.IraeNrIAxkI0eXN8TzTNbLhvt--Cc5FGs1IDSvBeoZQ

### Create a todo POST /todos
POST http://localhost:5000/todos
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzQzOTY1ODg4LCJleHAiOjE3NDQwNTIyODh9.IraeNrIAxkI0eXN8TzTNbLhvt--Cc5FGs1IDSvBeoZQ
Content-Type: application/json

{
    "task":"Finish coding"
}
